debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator ?? ?? ?? TODO


logging:
    level:
      com.fastcampus.projectboard: debug
      org.springframework.web.servlet: debug # request response ??? TODO
      org.hibernate.type.descriptor.sql.BasicBinder: trace # ???? ??, ? ??? ??? ??? ? ? ?? TODO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: boardserver
    password: abcd1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data.sql ??? ??? ??? ??? ?? TODO
    hibernate:
      ddl-auto: create
#    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always # data.sql ?? ????? TODO

---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test:
    database:
      replace: none # 전역설정, @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE) 대신
