spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: localuser
      password: 1234abcd
  batch:
    jdbc:
      initialize-schema: never
