drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity, /* 자동으로 값을 채워줌 */
    name varchar(255),
    primary key (id)
);

/* insert samples */
insert into member(name) values('spring');
insert into member(name) values('spring2');