spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # system.out 에 출력
        format_sql: true
        use_sql_comments: true # comment 에서 jpql 을 볼 수 있음

logging.level:
  org.hibernate.SQL: debug # logger 출력
#  org.hibernate.type: trace # 기본 쿼리에 바인딩 값 출력
